name: deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Staging
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          port: ${{ secrets.DEV_SSH_PORT }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: bash /app/renta_ueno/deploy.sh renta_ueno

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: SSH to Production
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          port: ${{ secrets.PROD_SSH_PORT }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: bash /app/renta_ueno/deploy.sh renta_ueno
